import { Item, ItemType, NodeType, Rarity } from './types';
import { ASSETS } from './assets';

export const MAP_LAYERS = 6;
export const MAX_HP_START = 50; 
export const HEAL_AMOUNT_REST = 20;
export const LOOT_OPEN_DURATION = 1500;

export const ENEMY_STATS = {
  [NodeType.ENEMY]: { hp: 40, damage: 10 },
  [NodeType.ELITE]: { hp: 120, damage: 15 },
  [NodeType.BOSS]: { hp: 300, damage: 25 },
};

export const BASE_PLAYER_DAMAGE = 25; 

// Initial Items Database
export const ITEMS: Record<string, Omit<Item, 'id'>> = {
  POTION: {
    type: ItemType.POTION_HEAL,
    name: 'Jamu Gendong',
    description: 'Minuman herbal penyegar (Heal 20 HP)',
    icon: '🌿',
    imageUrl: ASSETS.jamu,
    value: 20,
    price: 15,
    rarity: Rarity.COMMON,
  },
  BOMB: {
    type: ItemType.BOMB,
    name: 'Bambu Runcing',
    description: 'Semangat perjuangan! (50 DMG)',
    icon: '🎋',
    imageUrl: ASSETS.bambu,
    value: 50,
    price: 60,
    rarity: Rarity.UNCOMMON,
  },
  POTION_BIG: {
    type: ItemType.POTION_HEAL,
    name: 'Nasi Tumpeng',
    description: 'Syukuran kemenangan (Heal 50 HP)',
    icon: '🍚',
    imageUrl: ASSETS.tumpeng,
    value: 50,
    price: 50,
    rarity: Rarity.UNCOMMON,
  },
  DAGGER: {
    type: ItemType.WEAPON,
    name: 'Keris',
    description: 'Senjata tradisional (+5 ATK)',
    icon: '🗡️',
    imageUrl: ASSETS.keris,
    value: 5,
    price: 40,
    rarity: Rarity.COMMON,
  },
  SWORD: {
    type: ItemType.WEAPON,
    name: 'Parang',
    description: 'Tebasan mantap (+15 ATK)',
    icon: '🔪',
    imageUrl: ASSETS.parang,
    value: 15,
    price: 150,
    rarity: Rarity.UNCOMMON,
  },
  AXE: {
    type: ItemType.WEAPON,
    name: 'Klewang',
    description: 'Senjata tajam (+25 ATK)',
    icon: '⚔️',
    imageUrl: ASSETS.klewang,
    value: 25,
    price: 300,
    rarity: Rarity.RARE,
  },
  BANDAGE: {
    type: ItemType.ARMOR,
    name: 'Kain Perca',
    description: 'Perlindungan sederhana (+2 DEF)',
    icon: '🧣',
    imageUrl: ASSETS.perca,
    value: 2,
    price: 15,
    rarity: Rarity.COMMON,
  },
  RIBBON: {
    type: ItemType.ARMOR,
    name: 'Selendang',
    description: 'Anggun dan melindungi (+5 DEF)',
    icon: '🎗️',
    imageUrl: ASSETS.selendang,
    value: 5,
    price: 60,
    rarity: Rarity.UNCOMMON,
  },
  LOCKET: {
    type: ItemType.ARMOR,
    name: 'Kalung Emas',
    description: 'Harta karun (+15 DEF)',
    icon: '📿',
    imageUrl: ASSETS.kalung,
    value: 15,
    price: 200,
    rarity: Rarity.RARE,
  },
  ARMOR_PLATE: {
    type: ItemType.ARMOR,
    name: 'Baju Zirah',
    description: 'Perlindungan maksimal (+20 DEF)',
    icon: '🛡️',
    imageUrl: ASSETS.zirah,
    value: 20,
    price: 350,
    rarity: Rarity.LEGENDARY,
  },
  SCROLL: {
    type: ItemType.SCROLL_SKIP,
    name: 'Batik Sakti',
    description: 'Lewati satu pertanyaan sulit',
    icon: '👘',
    imageUrl: ASSETS.batik,
    value: 0,
    price: 30,
    rarity: Rarity.COMMON,
  },
  SCROLL_CHAOS: {
    type: ItemType.SCROLL_REROLL,
    name: 'Wayang Kulit',
    description: 'Ubah takdir peta (Reroll)',
    icon: '🎭',
    imageUrl: ASSETS.wayang,
    value: 0,
    price: 75,
    rarity: Rarity.RARE,
  }
};

// Lore Database
export const LORE_DATABASE: Record<string, { title: string, text: string }> = {
  'lore-1': { title: 'Sumpah Pemuda', text: '28 Oktober 1928: Satu Nusa, Satu Bangsa, Satu Bahasa. Tonggak persatuan pemuda Indonesia.' },
  'lore-2': { title: 'Proklamasi', text: '17 Agustus 1945: Soekarno-Hatta memproklamasikan kemerdekaan Indonesia di Jalan Pegangsaan Timur 56.' },
  'lore-3': { title: 'Legenda Danau Toba', text: 'Kisah Toba dan ikan mas ajaib yang membentuk danau vulkanik terbesar di dunia.' },
  'lore-4': { title: 'Candi Borobudur', text: 'Candi Buddha terbesar di dunia, dibangun pada abad ke-9 oleh Wangsa Syailendra.' },
  'lore-5': { title: 'Garuda Pancasila', text: 'Lambang negara Indonesia dengan semboyan Bhinneka Tunggal Ika: Berbeda-beda tetapi tetap satu.' },
};

export const MODIFIER_METADATA: Record<string, { name: string, description: string, icon: string }> = {
  NO_ELITES: { name: 'Peaceful Path', description: 'No Elite enemies will spawn.', icon: '🕊️' },
  NO_LOOT: { name: 'Poverty', description: 'No Treasure chests will spawn.', icon: '🚫' },
  NO_BOSSES: { name: 'Boss Rushless', description: 'Bosses are replaced by Elites.', icon: '❌' },
  HARDCORE: { name: 'Hardcore', description: 'Less time to answer questions.', icon: '⏱️' },
  EASY_MODE: { name: 'Easy Mode', description: 'More time to answer questions.', icon: '🐢' },
  DOUBLE_GOLD: { name: 'Gold Rush', description: 'Earn 2x Gold from battles.', icon: '💰' },
  HALF_HP: { name: 'Fragile', description: 'Start with 50% Max HP.', icon: '💔' },
  GLASS_CANNON: { name: 'Glass Cannon', description: 'Double Attack, but Half HP.', icon: '⚔️' },
  RICH_START: { name: 'Inheritance', description: 'Start with 100 Gold.', icon: '💎' },
};

export const UI_TEXT = {
  INDONESIAN: {
    title: "JELAJAH NUSANTARA",
    subtitle: "Petualangan Sang Penjelajah",
    start: "MULAI PETUALANGAN",
    configure: "ATUR PERJALANAN",
    difficulty: "TINGKAT KESULITAN",
    modifiers: "MODIFIKASI",
    active: "AKTIF",
    done: "SELESAI",
    menu: "MENU",
    return: "KEMBALI KE MENU",
    gameOver: "PERMAINAN BERAKHIR",
    victory: "MENANG!",
    refused: "Jangan menyerah, kawan!",
    shop: "WARUNG",
    inventory: "TAS",
    fight: "LAWAN",
    item: "BARANG",
    back: "KEMBALI",
    equip: "PAKAI",
    use: "GUNAKAN",
    empty: "Kosong...",
    generating: "Mencari info...",
    solve: "Jawab!",
    correct: "BENAR!",
    wrong: "SALAH!",
    won: "MENANG!",
    skipped: "DILEWATI!",
    critical: "SERANGAN KRITIS!",
    timeUp: "WAKTU HABIS!",
    ready: "Siap?",
    enemyTurn: "Giliran Musuh",
    equipMap: "Pakai hanya di Peta!",
    used: "Menggunakan",
    dealt: "Memberikan",
    dmg: "DMG",
    recovered: "PULIH",
    runModifiers: "MODIFIKASI PERJALANAN",
    summary: "RINGKASAN",
    enemiesDefeated: "Musuh Dikalahkan",
    goldEarned: "Emas Didapat",
    timeTaken: "Waktu",
    highestLayer: "Lantai Tertinggi"
  },
  ENGLISH: {
    title: "ARCHIPELAGO QUEST",
    subtitle: "The Explorer's Journey",
    start: "START ADVENTURE",
    configure: "CONFIGURE RUN",
    difficulty: "DIFFICULTY",
    modifiers: "MODIFIERS",
    active: "ACTIVE",
    done: "DONE",
    menu: "MENU",
    return: "RETURN TO MENU",
    gameOver: "GAME OVER",
    victory: "VICTORY!",
    refused: "But it refused.",
    shop: "SHOP",
    inventory: "INVENTORY",
    fight: "FIGHT",
    item: "ITEM",
    back: "BACK",
    equip: "EQUIP",
    use: "USE",
    empty: "Empty...",
    generating: "Generating...",
    solve: "Solve!",
    correct: "CORRECT!",
    wrong: "WRONG!",
    won: "YOU WON!",
    skipped: "SKIPPED!",
    critical: "CRITICAL HIT!",
    timeUp: "TIME'S UP!",
    ready: "Ready?",
    enemyTurn: "Enemy turn over.",
    equipMap: "Equip only on Map!",
    used: "Used",
    dealt: "Dealt",
    dmg: "DMG",
    recovered: "RECOVERED",
    runModifiers: "RUN MODIFIERS",
    summary: "SUMMARY",
    enemiesDefeated: "Enemies Defeated",
    goldEarned: "Gold Earned",
    timeTaken: "Time Taken",
    highestLayer: "Highest Layer"
  }
};

export const INITIAL_PLAYER = {
  hp: 20, 
  maxHp: 20,
  gold: 0,
  attack: 0,
  defense: 0,
  inventory: [],
  equippedWeapon: null,
  equippedArmor: null,
  currentNodeId: null,
  history: [],
  lore: [],
  runStats: {
    enemiesDefeated: 0,
    goldEarned: 0,
    startTime: 0,
    highestLayer: 0,
    runId: ''
  },
  usedQuestions: []
};
